//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficCount.Presentation.TCInsert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TCInsert.ITCInsert")]
    public interface ITCInsert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCInsert/DelTCbySiteID", ReplyAction="http://tempuri.org/ITCInsert/DelTCbySiteIDResponse")]
        bool DelTCbySiteID(string siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCInsert/InsertTCAxlesDetails", ReplyAction="http://tempuri.org/ITCInsert/InsertTCAxlesDetailsResponse")]
        bool InsertTCAxlesDetails(
                    string siteID, 
                    string lane, 
                    string bound, 
                    System.DateTime timeStart, 
                    System.DateTime timeEnd, 
                    string timeCaptured, 
                    string location, 
                    System.Nullable<int> motorCycles, 
                    int passengerCars, 
                    System.Nullable<int> twoAxleFourTires, 
                    System.Nullable<int> bues, 
                    System.Nullable<int> twoAxlesSixTires, 
                    System.Nullable<int> threeAxlesSingleUnitTruck, 
                    System.Nullable<int> fourOrMoreAxleSingleUnitTruck, 
                    System.Nullable<int> fourOrLessAxleSingleTrailer, 
                    System.Nullable<int> fiveAleSingleTrailerTruck, 
                    System.Nullable<int> sixOrMoreAxleSingleTrailerTruck, 
                    System.Nullable<int> fiveLessAxleMultiTrailerTruck, 
                    System.Nullable<int> sixAxleMultiTrailerTruck, 
                    System.Nullable<int> sevenMoreAxleMultiTrailerTruck, 
                    System.Nullable<double> spMean, 
                    System.Nullable<double> vpp85);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCInsert/InsertTCSpeedDetails", ReplyAction="http://tempuri.org/ITCInsert/InsertTCSpeedDetailsResponse")]
        bool InsertTCSpeedDetails(
                    string siteID, 
                    string lane, 
                    string bound, 
                    System.DateTime timeStart, 
                    System.DateTime timeEnd, 
                    string timeCaptured, 
                    string location, 
                    int sp0To10, 
                    int sp10To20, 
                    int sp20To30, 
                    int sp30To40, 
                    int sp40To50, 
                    int sp50To60, 
                    int sp60To70, 
                    int sp70To80, 
                    int sp80To90, 
                    int sp90To100, 
                    int sp100To110, 
                    int sp110To120, 
                    int sp120To130, 
                    int sp130To140, 
                    int sp140To150, 
                    int sp150To160, 
                    int sp160To200, 
                    double spMean, 
                    double Vpp85);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCInsert/InsertTCAxlesSummary", ReplyAction="http://tempuri.org/ITCInsert/InsertTCAxlesSummaryResponse")]
        bool InsertTCAxlesSummary(
                    string siteID, 
                    string lane, 
                    string bound, 
                    System.DateTime timeStart, 
                    System.DateTime timeEnd, 
                    string timeCaptured, 
                    string location, 
                    System.Nullable<int> motorCycles, 
                    int passengerCars, 
                    System.Nullable<int> twoAxleFourTires, 
                    System.Nullable<int> bues, 
                    System.Nullable<int> twoAxlesSixTires, 
                    System.Nullable<int> threeAxlesSingleUnitTruck, 
                    System.Nullable<int> fourOrMoreAxleSingleUnitTruck, 
                    System.Nullable<int> fourOrLessAxleSingleTrailer, 
                    System.Nullable<int> fiveAleSingleTrailerTruck, 
                    System.Nullable<int> sixOrMoreAxleSingleTrailerTruck, 
                    System.Nullable<int> fiveLessAxleMultiTrailerTruck, 
                    System.Nullable<int> sixAxleMultiTrailerTruck, 
                    System.Nullable<int> sevenMoreAxleMultiTrailerTruck, 
                    System.Nullable<double> spMean, 
                    System.Nullable<double> vpp85);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCInsert/InsertTCSpeedSummary", ReplyAction="http://tempuri.org/ITCInsert/InsertTCSpeedSummaryResponse")]
        bool InsertTCSpeedSummary(
                    string siteID, 
                    string lane, 
                    string bound, 
                    System.DateTime timeStart, 
                    System.DateTime timeEnd, 
                    string timeCaptured, 
                    string location, 
                    int sp0To10, 
                    int sp10To20, 
                    int sp20To30, 
                    int sp30To40, 
                    int sp40To50, 
                    int sp50To60, 
                    int sp60To70, 
                    int sp70To80, 
                    int sp80To90, 
                    int sp90To100, 
                    int sp100To110, 
                    int sp110To120, 
                    int sp120To130, 
                    int sp130To140, 
                    int sp140To150, 
                    int sp150To160, 
                    int sp160To200, 
                    double spMean, 
                    double Vpp85);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCInsert/InsertTCSummary", ReplyAction="http://tempuri.org/ITCInsert/InsertTCSummaryResponse")]
        bool InsertTCSummary(string site, int twp, string location, System.DateTime timeStart, int numberOfVehicle, string postedLimit, string percentile85, string percentageTrucks, string road1, string road2, string dir, string insertedBy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITCInsertChannel : TrafficCount.Presentation.TCInsert.ITCInsert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCInsertClient : System.ServiceModel.ClientBase<TrafficCount.Presentation.TCInsert.ITCInsert>, TrafficCount.Presentation.TCInsert.ITCInsert {
        
        public TCInsertClient() {
        }
        
        public TCInsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCInsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCInsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCInsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DelTCbySiteID(string siteID) {
            return base.Channel.DelTCbySiteID(siteID);
        }
        
        public bool InsertTCAxlesDetails(
                    string siteID, 
                    string lane, 
                    string bound, 
                    System.DateTime timeStart, 
                    System.DateTime timeEnd, 
                    string timeCaptured, 
                    string location, 
                    System.Nullable<int> motorCycles, 
                    int passengerCars, 
                    System.Nullable<int> twoAxleFourTires, 
                    System.Nullable<int> bues, 
                    System.Nullable<int> twoAxlesSixTires, 
                    System.Nullable<int> threeAxlesSingleUnitTruck, 
                    System.Nullable<int> fourOrMoreAxleSingleUnitTruck, 
                    System.Nullable<int> fourOrLessAxleSingleTrailer, 
                    System.Nullable<int> fiveAleSingleTrailerTruck, 
                    System.Nullable<int> sixOrMoreAxleSingleTrailerTruck, 
                    System.Nullable<int> fiveLessAxleMultiTrailerTruck, 
                    System.Nullable<int> sixAxleMultiTrailerTruck, 
                    System.Nullable<int> sevenMoreAxleMultiTrailerTruck, 
                    System.Nullable<double> spMean, 
                    System.Nullable<double> vpp85) {
            return base.Channel.InsertTCAxlesDetails(siteID, lane, bound, timeStart, timeEnd, timeCaptured, location, motorCycles, passengerCars, twoAxleFourTires, bues, twoAxlesSixTires, threeAxlesSingleUnitTruck, fourOrMoreAxleSingleUnitTruck, fourOrLessAxleSingleTrailer, fiveAleSingleTrailerTruck, sixOrMoreAxleSingleTrailerTruck, fiveLessAxleMultiTrailerTruck, sixAxleMultiTrailerTruck, sevenMoreAxleMultiTrailerTruck, spMean, vpp85);
        }
        
        public bool InsertTCSpeedDetails(
                    string siteID, 
                    string lane, 
                    string bound, 
                    System.DateTime timeStart, 
                    System.DateTime timeEnd, 
                    string timeCaptured, 
                    string location, 
                    int sp0To10, 
                    int sp10To20, 
                    int sp20To30, 
                    int sp30To40, 
                    int sp40To50, 
                    int sp50To60, 
                    int sp60To70, 
                    int sp70To80, 
                    int sp80To90, 
                    int sp90To100, 
                    int sp100To110, 
                    int sp110To120, 
                    int sp120To130, 
                    int sp130To140, 
                    int sp140To150, 
                    int sp150To160, 
                    int sp160To200, 
                    double spMean, 
                    double Vpp85) {
            return base.Channel.InsertTCSpeedDetails(siteID, lane, bound, timeStart, timeEnd, timeCaptured, location, sp0To10, sp10To20, sp20To30, sp30To40, sp40To50, sp50To60, sp60To70, sp70To80, sp80To90, sp90To100, sp100To110, sp110To120, sp120To130, sp130To140, sp140To150, sp150To160, sp160To200, spMean, Vpp85);
        }
        
        public bool InsertTCAxlesSummary(
                    string siteID, 
                    string lane, 
                    string bound, 
                    System.DateTime timeStart, 
                    System.DateTime timeEnd, 
                    string timeCaptured, 
                    string location, 
                    System.Nullable<int> motorCycles, 
                    int passengerCars, 
                    System.Nullable<int> twoAxleFourTires, 
                    System.Nullable<int> bues, 
                    System.Nullable<int> twoAxlesSixTires, 
                    System.Nullable<int> threeAxlesSingleUnitTruck, 
                    System.Nullable<int> fourOrMoreAxleSingleUnitTruck, 
                    System.Nullable<int> fourOrLessAxleSingleTrailer, 
                    System.Nullable<int> fiveAleSingleTrailerTruck, 
                    System.Nullable<int> sixOrMoreAxleSingleTrailerTruck, 
                    System.Nullable<int> fiveLessAxleMultiTrailerTruck, 
                    System.Nullable<int> sixAxleMultiTrailerTruck, 
                    System.Nullable<int> sevenMoreAxleMultiTrailerTruck, 
                    System.Nullable<double> spMean, 
                    System.Nullable<double> vpp85) {
            return base.Channel.InsertTCAxlesSummary(siteID, lane, bound, timeStart, timeEnd, timeCaptured, location, motorCycles, passengerCars, twoAxleFourTires, bues, twoAxlesSixTires, threeAxlesSingleUnitTruck, fourOrMoreAxleSingleUnitTruck, fourOrLessAxleSingleTrailer, fiveAleSingleTrailerTruck, sixOrMoreAxleSingleTrailerTruck, fiveLessAxleMultiTrailerTruck, sixAxleMultiTrailerTruck, sevenMoreAxleMultiTrailerTruck, spMean, vpp85);
        }
        
        public bool InsertTCSpeedSummary(
                    string siteID, 
                    string lane, 
                    string bound, 
                    System.DateTime timeStart, 
                    System.DateTime timeEnd, 
                    string timeCaptured, 
                    string location, 
                    int sp0To10, 
                    int sp10To20, 
                    int sp20To30, 
                    int sp30To40, 
                    int sp40To50, 
                    int sp50To60, 
                    int sp60To70, 
                    int sp70To80, 
                    int sp80To90, 
                    int sp90To100, 
                    int sp100To110, 
                    int sp110To120, 
                    int sp120To130, 
                    int sp130To140, 
                    int sp140To150, 
                    int sp150To160, 
                    int sp160To200, 
                    double spMean, 
                    double Vpp85) {
            return base.Channel.InsertTCSpeedSummary(siteID, lane, bound, timeStart, timeEnd, timeCaptured, location, sp0To10, sp10To20, sp20To30, sp30To40, sp40To50, sp50To60, sp60To70, sp70To80, sp80To90, sp90To100, sp100To110, sp110To120, sp120To130, sp130To140, sp140To150, sp150To160, sp160To200, spMean, Vpp85);
        }
        
        public bool InsertTCSummary(string site, int twp, string location, System.DateTime timeStart, int numberOfVehicle, string postedLimit, string percentile85, string percentageTrucks, string road1, string road2, string dir, string insertedBy) {
            return base.Channel.InsertTCSummary(site, twp, location, timeStart, numberOfVehicle, postedLimit, percentile85, percentageTrucks, road1, road2, dir, insertedBy);
        }
    }
}
