//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficCount.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCSummary
    {
        public int ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
        public string vchSiteID { get; set; }
        public string LegalDesc { get; set; }
        public Nullable<int> calcYearOfCount { get; set; }
        public Nullable<int> intTWP { get; set; }
        public string Road1 { get; set; }
        public string Road2 { get; set; }
        public string Dir { get; set; }
        public string SensorID { get; set; }
        public string vchLocation { get; set; }
        public Nullable<System.DateTime> dteDateOfCount { get; set; }
        public Nullable<int> intNumofVehicles { get; set; }
        public string vchTypeofCounter { get; set; }
        public string vchPostedLimit { get; set; }
        public string vch85Percentile { get; set; }
        public Nullable<int> TruckCount { get; set; }
        public string vchPercentageTrucks { get; set; }
        public string Comment { get; set; }
        public string LinkToHistory { get; set; }
        public string LinkToSummary { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string InsertUser { get; set; }
    }
}
