//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficCount.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficCountSensor
    {
        public int ogr_fid { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
        public string road_1 { get; set; }
        public string road_2 { get; set; }
        public Nullable<int> distance_m { get; set; }
        public string linktohistory { get; set; }
        public string direction { get; set; }
    }
}
