//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficCount.Presentation.TCService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spTCAxlesDetails_Result", Namespace="http://schemas.datacontract.org/2004/07/TrafficCount.Domain")]
    [System.SerializableAttribute()]
    public partial class spTCAxlesDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BusesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FiveAxleSignleTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FiveLessAxleMultiTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FourOrLessAxleSingleTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FourOrMoreAxleSignleUnitTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LaneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MotorCyclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PassengerCarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SevenMoreAxleMultiTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SixAxleMultiTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SixOrMoreAxleSignleTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SpMeanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ThreeAxleSingleUnitTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeCapturedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TruckCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TwoAxleFourTiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TwoAxleSixTiresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Buses {
            get {
                return this.BusesField;
            }
            set {
                if ((this.BusesField.Equals(value) != true)) {
                    this.BusesField = value;
                    this.RaisePropertyChanged("Buses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FiveAxleSignleTrailerTruck {
            get {
                return this.FiveAxleSignleTrailerTruckField;
            }
            set {
                if ((this.FiveAxleSignleTrailerTruckField.Equals(value) != true)) {
                    this.FiveAxleSignleTrailerTruckField = value;
                    this.RaisePropertyChanged("FiveAxleSignleTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FiveLessAxleMultiTrailerTruck {
            get {
                return this.FiveLessAxleMultiTrailerTruckField;
            }
            set {
                if ((this.FiveLessAxleMultiTrailerTruckField.Equals(value) != true)) {
                    this.FiveLessAxleMultiTrailerTruckField = value;
                    this.RaisePropertyChanged("FiveLessAxleMultiTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FourOrLessAxleSingleTrailerTruck {
            get {
                return this.FourOrLessAxleSingleTrailerTruckField;
            }
            set {
                if ((this.FourOrLessAxleSingleTrailerTruckField.Equals(value) != true)) {
                    this.FourOrLessAxleSingleTrailerTruckField = value;
                    this.RaisePropertyChanged("FourOrLessAxleSingleTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FourOrMoreAxleSignleUnitTruck {
            get {
                return this.FourOrMoreAxleSignleUnitTruckField;
            }
            set {
                if ((this.FourOrMoreAxleSignleUnitTruckField.Equals(value) != true)) {
                    this.FourOrMoreAxleSignleUnitTruckField = value;
                    this.RaisePropertyChanged("FourOrMoreAxleSignleUnitTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lane {
            get {
                return this.LaneField;
            }
            set {
                if ((object.ReferenceEquals(this.LaneField, value) != true)) {
                    this.LaneField = value;
                    this.RaisePropertyChanged("Lane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MotorCycles {
            get {
                return this.MotorCyclesField;
            }
            set {
                if ((this.MotorCyclesField.Equals(value) != true)) {
                    this.MotorCyclesField = value;
                    this.RaisePropertyChanged("MotorCycles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PassengerCars {
            get {
                return this.PassengerCarsField;
            }
            set {
                if ((this.PassengerCarsField.Equals(value) != true)) {
                    this.PassengerCarsField = value;
                    this.RaisePropertyChanged("PassengerCars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SevenMoreAxleMultiTrailerTruck {
            get {
                return this.SevenMoreAxleMultiTrailerTruckField;
            }
            set {
                if ((this.SevenMoreAxleMultiTrailerTruckField.Equals(value) != true)) {
                    this.SevenMoreAxleMultiTrailerTruckField = value;
                    this.RaisePropertyChanged("SevenMoreAxleMultiTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SixAxleMultiTrailerTruck {
            get {
                return this.SixAxleMultiTrailerTruckField;
            }
            set {
                if ((this.SixAxleMultiTrailerTruckField.Equals(value) != true)) {
                    this.SixAxleMultiTrailerTruckField = value;
                    this.RaisePropertyChanged("SixAxleMultiTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SixOrMoreAxleSignleTrailerTruck {
            get {
                return this.SixOrMoreAxleSignleTrailerTruckField;
            }
            set {
                if ((this.SixOrMoreAxleSignleTrailerTruckField.Equals(value) != true)) {
                    this.SixOrMoreAxleSignleTrailerTruckField = value;
                    this.RaisePropertyChanged("SixOrMoreAxleSignleTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SpMean {
            get {
                return this.SpMeanField;
            }
            set {
                if ((this.SpMeanField.Equals(value) != true)) {
                    this.SpMeanField = value;
                    this.RaisePropertyChanged("SpMean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ThreeAxleSingleUnitTruck {
            get {
                return this.ThreeAxleSingleUnitTruckField;
            }
            set {
                if ((this.ThreeAxleSingleUnitTruckField.Equals(value) != true)) {
                    this.ThreeAxleSingleUnitTruckField = value;
                    this.RaisePropertyChanged("ThreeAxleSingleUnitTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeCaptured {
            get {
                return this.TimeCapturedField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeCapturedField, value) != true)) {
                    this.TimeCapturedField = value;
                    this.RaisePropertyChanged("TimeCaptured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TruckCount {
            get {
                return this.TruckCountField;
            }
            set {
                if ((this.TruckCountField.Equals(value) != true)) {
                    this.TruckCountField = value;
                    this.RaisePropertyChanged("TruckCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TwoAxleFourTires {
            get {
                return this.TwoAxleFourTiresField;
            }
            set {
                if ((this.TwoAxleFourTiresField.Equals(value) != true)) {
                    this.TwoAxleFourTiresField = value;
                    this.RaisePropertyChanged("TwoAxleFourTires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TwoAxleSixTires {
            get {
                return this.TwoAxleSixTiresField;
            }
            set {
                if ((this.TwoAxleSixTiresField.Equals(value) != true)) {
                    this.TwoAxleSixTiresField = value;
                    this.RaisePropertyChanged("TwoAxleSixTires");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spTCSpeedDetails_Result", Namespace="http://schemas.datacontract.org/2004/07/TrafficCount.Domain")]
    [System.SerializableAttribute()]
    public partial class spTCSpeedDetails_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LaneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp0To10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp100To110Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp10To20Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp110To120Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp120To130Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp130To140Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp140To150Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp150To160Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp160To200Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp20To30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp30To40Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp40To50Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp50To60Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp60To70Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp70To80Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp80To90Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp90To100Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SpMeanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeCapturedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lane {
            get {
                return this.LaneField;
            }
            set {
                if ((object.ReferenceEquals(this.LaneField, value) != true)) {
                    this.LaneField = value;
                    this.RaisePropertyChanged("Lane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp0To10 {
            get {
                return this.Sp0To10Field;
            }
            set {
                if ((this.Sp0To10Field.Equals(value) != true)) {
                    this.Sp0To10Field = value;
                    this.RaisePropertyChanged("Sp0To10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp100To110 {
            get {
                return this.Sp100To110Field;
            }
            set {
                if ((this.Sp100To110Field.Equals(value) != true)) {
                    this.Sp100To110Field = value;
                    this.RaisePropertyChanged("Sp100To110");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp10To20 {
            get {
                return this.Sp10To20Field;
            }
            set {
                if ((this.Sp10To20Field.Equals(value) != true)) {
                    this.Sp10To20Field = value;
                    this.RaisePropertyChanged("Sp10To20");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp110To120 {
            get {
                return this.Sp110To120Field;
            }
            set {
                if ((this.Sp110To120Field.Equals(value) != true)) {
                    this.Sp110To120Field = value;
                    this.RaisePropertyChanged("Sp110To120");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp120To130 {
            get {
                return this.Sp120To130Field;
            }
            set {
                if ((this.Sp120To130Field.Equals(value) != true)) {
                    this.Sp120To130Field = value;
                    this.RaisePropertyChanged("Sp120To130");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp130To140 {
            get {
                return this.Sp130To140Field;
            }
            set {
                if ((this.Sp130To140Field.Equals(value) != true)) {
                    this.Sp130To140Field = value;
                    this.RaisePropertyChanged("Sp130To140");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp140To150 {
            get {
                return this.Sp140To150Field;
            }
            set {
                if ((this.Sp140To150Field.Equals(value) != true)) {
                    this.Sp140To150Field = value;
                    this.RaisePropertyChanged("Sp140To150");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp150To160 {
            get {
                return this.Sp150To160Field;
            }
            set {
                if ((this.Sp150To160Field.Equals(value) != true)) {
                    this.Sp150To160Field = value;
                    this.RaisePropertyChanged("Sp150To160");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp160To200 {
            get {
                return this.Sp160To200Field;
            }
            set {
                if ((this.Sp160To200Field.Equals(value) != true)) {
                    this.Sp160To200Field = value;
                    this.RaisePropertyChanged("Sp160To200");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp20To30 {
            get {
                return this.Sp20To30Field;
            }
            set {
                if ((this.Sp20To30Field.Equals(value) != true)) {
                    this.Sp20To30Field = value;
                    this.RaisePropertyChanged("Sp20To30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp30To40 {
            get {
                return this.Sp30To40Field;
            }
            set {
                if ((this.Sp30To40Field.Equals(value) != true)) {
                    this.Sp30To40Field = value;
                    this.RaisePropertyChanged("Sp30To40");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp40To50 {
            get {
                return this.Sp40To50Field;
            }
            set {
                if ((this.Sp40To50Field.Equals(value) != true)) {
                    this.Sp40To50Field = value;
                    this.RaisePropertyChanged("Sp40To50");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp50To60 {
            get {
                return this.Sp50To60Field;
            }
            set {
                if ((this.Sp50To60Field.Equals(value) != true)) {
                    this.Sp50To60Field = value;
                    this.RaisePropertyChanged("Sp50To60");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp60To70 {
            get {
                return this.Sp60To70Field;
            }
            set {
                if ((this.Sp60To70Field.Equals(value) != true)) {
                    this.Sp60To70Field = value;
                    this.RaisePropertyChanged("Sp60To70");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp70To80 {
            get {
                return this.Sp70To80Field;
            }
            set {
                if ((this.Sp70To80Field.Equals(value) != true)) {
                    this.Sp70To80Field = value;
                    this.RaisePropertyChanged("Sp70To80");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp80To90 {
            get {
                return this.Sp80To90Field;
            }
            set {
                if ((this.Sp80To90Field.Equals(value) != true)) {
                    this.Sp80To90Field = value;
                    this.RaisePropertyChanged("Sp80To90");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp90To100 {
            get {
                return this.Sp90To100Field;
            }
            set {
                if ((this.Sp90To100Field.Equals(value) != true)) {
                    this.Sp90To100Field = value;
                    this.RaisePropertyChanged("Sp90To100");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SpMean {
            get {
                return this.SpMeanField;
            }
            set {
                if ((this.SpMeanField.Equals(value) != true)) {
                    this.SpMeanField = value;
                    this.RaisePropertyChanged("SpMean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeCaptured {
            get {
                return this.TimeCapturedField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeCapturedField, value) != true)) {
                    this.TimeCapturedField = value;
                    this.RaisePropertyChanged("TimeCaptured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spTCSummaryByLoc_Result", Namespace="http://schemas.datacontract.org/2004/07/TrafficCount.Domain")]
    [System.SerializableAttribute()]
    public partial class spTCSummaryByLoc_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkToHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkToSummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumofVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PercentageTrucksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Percentile85Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostedLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Road1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Road2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TWPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir {
            get {
                return this.DirField;
            }
            set {
                if ((object.ReferenceEquals(this.DirField, value) != true)) {
                    this.DirField = value;
                    this.RaisePropertyChanged("Dir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalDesc {
            get {
                return this.LegalDescField;
            }
            set {
                if ((object.ReferenceEquals(this.LegalDescField, value) != true)) {
                    this.LegalDescField = value;
                    this.RaisePropertyChanged("LegalDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkToHistory {
            get {
                return this.LinkToHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkToHistoryField, value) != true)) {
                    this.LinkToHistoryField = value;
                    this.RaisePropertyChanged("LinkToHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkToSummary {
            get {
                return this.LinkToSummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkToSummaryField, value) != true)) {
                    this.LinkToSummaryField = value;
                    this.RaisePropertyChanged("LinkToSummary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumofVolume {
            get {
                return this.NumofVolumeField;
            }
            set {
                if ((this.NumofVolumeField.Equals(value) != true)) {
                    this.NumofVolumeField = value;
                    this.RaisePropertyChanged("NumofVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PercentageTrucks {
            get {
                return this.PercentageTrucksField;
            }
            set {
                if ((object.ReferenceEquals(this.PercentageTrucksField, value) != true)) {
                    this.PercentageTrucksField = value;
                    this.RaisePropertyChanged("PercentageTrucks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Percentile85 {
            get {
                return this.Percentile85Field;
            }
            set {
                if ((object.ReferenceEquals(this.Percentile85Field, value) != true)) {
                    this.Percentile85Field = value;
                    this.RaisePropertyChanged("Percentile85");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostedLimit {
            get {
                return this.PostedLimitField;
            }
            set {
                if ((object.ReferenceEquals(this.PostedLimitField, value) != true)) {
                    this.PostedLimitField = value;
                    this.RaisePropertyChanged("PostedLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road1 {
            get {
                return this.Road1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Road1Field, value) != true)) {
                    this.Road1Field = value;
                    this.RaisePropertyChanged("Road1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road2 {
            get {
                return this.Road2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Road2Field, value) != true)) {
                    this.Road2Field = value;
                    this.RaisePropertyChanged("Road2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteIDField, value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TWP {
            get {
                return this.TWPField;
            }
            set {
                if ((this.TWPField.Equals(value) != true)) {
                    this.TWPField = value;
                    this.RaisePropertyChanged("TWP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spTCSummaryBySite_Result", Namespace="http://schemas.datacontract.org/2004/07/TrafficCount.Domain")]
    [System.SerializableAttribute()]
    public partial class spTCSummaryBySite_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkToHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkToSummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumofVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PercentageTrucksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Percentile85Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostedLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Road1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Road2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TWPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir {
            get {
                return this.DirField;
            }
            set {
                if ((object.ReferenceEquals(this.DirField, value) != true)) {
                    this.DirField = value;
                    this.RaisePropertyChanged("Dir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalDesc {
            get {
                return this.LegalDescField;
            }
            set {
                if ((object.ReferenceEquals(this.LegalDescField, value) != true)) {
                    this.LegalDescField = value;
                    this.RaisePropertyChanged("LegalDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkToHistory {
            get {
                return this.LinkToHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkToHistoryField, value) != true)) {
                    this.LinkToHistoryField = value;
                    this.RaisePropertyChanged("LinkToHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkToSummary {
            get {
                return this.LinkToSummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkToSummaryField, value) != true)) {
                    this.LinkToSummaryField = value;
                    this.RaisePropertyChanged("LinkToSummary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumofVolume {
            get {
                return this.NumofVolumeField;
            }
            set {
                if ((this.NumofVolumeField.Equals(value) != true)) {
                    this.NumofVolumeField = value;
                    this.RaisePropertyChanged("NumofVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PercentageTrucks {
            get {
                return this.PercentageTrucksField;
            }
            set {
                if ((object.ReferenceEquals(this.PercentageTrucksField, value) != true)) {
                    this.PercentageTrucksField = value;
                    this.RaisePropertyChanged("PercentageTrucks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Percentile85 {
            get {
                return this.Percentile85Field;
            }
            set {
                if ((object.ReferenceEquals(this.Percentile85Field, value) != true)) {
                    this.Percentile85Field = value;
                    this.RaisePropertyChanged("Percentile85");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostedLimit {
            get {
                return this.PostedLimitField;
            }
            set {
                if ((object.ReferenceEquals(this.PostedLimitField, value) != true)) {
                    this.PostedLimitField = value;
                    this.RaisePropertyChanged("PostedLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road1 {
            get {
                return this.Road1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Road1Field, value) != true)) {
                    this.Road1Field = value;
                    this.RaisePropertyChanged("Road1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road2 {
            get {
                return this.Road2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Road2Field, value) != true)) {
                    this.Road2Field = value;
                    this.RaisePropertyChanged("Road2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteIDField, value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TWP {
            get {
                return this.TWPField;
            }
            set {
                if ((this.TWPField.Equals(value) != true)) {
                    this.TWPField = value;
                    this.RaisePropertyChanged("TWP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spTCSummaryOneBySite_Result", Namespace="http://schemas.datacontract.org/2004/07/TrafficCount.Domain")]
    [System.SerializableAttribute()]
    public partial class spTCSummaryOneBySite_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkToHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinktoSummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumofVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PercentageTrucksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Percentile85Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostedLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Road1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Road2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TWPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir {
            get {
                return this.DirField;
            }
            set {
                if ((object.ReferenceEquals(this.DirField, value) != true)) {
                    this.DirField = value;
                    this.RaisePropertyChanged("Dir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalDesc {
            get {
                return this.LegalDescField;
            }
            set {
                if ((object.ReferenceEquals(this.LegalDescField, value) != true)) {
                    this.LegalDescField = value;
                    this.RaisePropertyChanged("LegalDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkToHistory {
            get {
                return this.LinkToHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkToHistoryField, value) != true)) {
                    this.LinkToHistoryField = value;
                    this.RaisePropertyChanged("LinkToHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinktoSummary {
            get {
                return this.LinktoSummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.LinktoSummaryField, value) != true)) {
                    this.LinktoSummaryField = value;
                    this.RaisePropertyChanged("LinktoSummary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumofVolume {
            get {
                return this.NumofVolumeField;
            }
            set {
                if ((this.NumofVolumeField.Equals(value) != true)) {
                    this.NumofVolumeField = value;
                    this.RaisePropertyChanged("NumofVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PercentageTrucks {
            get {
                return this.PercentageTrucksField;
            }
            set {
                if ((object.ReferenceEquals(this.PercentageTrucksField, value) != true)) {
                    this.PercentageTrucksField = value;
                    this.RaisePropertyChanged("PercentageTrucks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Percentile85 {
            get {
                return this.Percentile85Field;
            }
            set {
                if ((object.ReferenceEquals(this.Percentile85Field, value) != true)) {
                    this.Percentile85Field = value;
                    this.RaisePropertyChanged("Percentile85");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostedLimit {
            get {
                return this.PostedLimitField;
            }
            set {
                if ((object.ReferenceEquals(this.PostedLimitField, value) != true)) {
                    this.PostedLimitField = value;
                    this.RaisePropertyChanged("PostedLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road1 {
            get {
                return this.Road1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Road1Field, value) != true)) {
                    this.Road1Field = value;
                    this.RaisePropertyChanged("Road1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Road2 {
            get {
                return this.Road2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Road2Field, value) != true)) {
                    this.Road2Field = value;
                    this.RaisePropertyChanged("Road2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteIDField, value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TWP {
            get {
                return this.TWPField;
            }
            set {
                if ((this.TWPField.Equals(value) != true)) {
                    this.TWPField = value;
                    this.RaisePropertyChanged("TWP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spTCAxlesSummaryBySite_Result", Namespace="http://schemas.datacontract.org/2004/07/TrafficCount.Domain")]
    [System.SerializableAttribute()]
    public partial class spTCAxlesSummaryBySite_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BusesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FiveAxleSignleTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FiveLessAxleMultiTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FourOrLessAxleSingleTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FourOrMoreAxleSignleUnitTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LaneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MotorCyclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PassengerCarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SevenMoreAxleMultiTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SixAxleMultiTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SixOrMoreAxleSignleTrailerTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SpMeanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ThreeAxleSingleUnitTruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeCapturedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TruckCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TwoAxleFourTiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TwoAxleSixTiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> Vpp85Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bound {
            get {
                return this.BoundField;
            }
            set {
                if ((object.ReferenceEquals(this.BoundField, value) != true)) {
                    this.BoundField = value;
                    this.RaisePropertyChanged("Bound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Buses {
            get {
                return this.BusesField;
            }
            set {
                if ((this.BusesField.Equals(value) != true)) {
                    this.BusesField = value;
                    this.RaisePropertyChanged("Buses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FiveAxleSignleTrailerTruck {
            get {
                return this.FiveAxleSignleTrailerTruckField;
            }
            set {
                if ((this.FiveAxleSignleTrailerTruckField.Equals(value) != true)) {
                    this.FiveAxleSignleTrailerTruckField = value;
                    this.RaisePropertyChanged("FiveAxleSignleTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FiveLessAxleMultiTrailerTruck {
            get {
                return this.FiveLessAxleMultiTrailerTruckField;
            }
            set {
                if ((this.FiveLessAxleMultiTrailerTruckField.Equals(value) != true)) {
                    this.FiveLessAxleMultiTrailerTruckField = value;
                    this.RaisePropertyChanged("FiveLessAxleMultiTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FourOrLessAxleSingleTrailerTruck {
            get {
                return this.FourOrLessAxleSingleTrailerTruckField;
            }
            set {
                if ((this.FourOrLessAxleSingleTrailerTruckField.Equals(value) != true)) {
                    this.FourOrLessAxleSingleTrailerTruckField = value;
                    this.RaisePropertyChanged("FourOrLessAxleSingleTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FourOrMoreAxleSignleUnitTruck {
            get {
                return this.FourOrMoreAxleSignleUnitTruckField;
            }
            set {
                if ((this.FourOrMoreAxleSignleUnitTruckField.Equals(value) != true)) {
                    this.FourOrMoreAxleSignleUnitTruckField = value;
                    this.RaisePropertyChanged("FourOrMoreAxleSignleUnitTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lane {
            get {
                return this.LaneField;
            }
            set {
                if ((object.ReferenceEquals(this.LaneField, value) != true)) {
                    this.LaneField = value;
                    this.RaisePropertyChanged("Lane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MotorCycles {
            get {
                return this.MotorCyclesField;
            }
            set {
                if ((this.MotorCyclesField.Equals(value) != true)) {
                    this.MotorCyclesField = value;
                    this.RaisePropertyChanged("MotorCycles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PassengerCars {
            get {
                return this.PassengerCarsField;
            }
            set {
                if ((this.PassengerCarsField.Equals(value) != true)) {
                    this.PassengerCarsField = value;
                    this.RaisePropertyChanged("PassengerCars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SevenMoreAxleMultiTrailerTruck {
            get {
                return this.SevenMoreAxleMultiTrailerTruckField;
            }
            set {
                if ((this.SevenMoreAxleMultiTrailerTruckField.Equals(value) != true)) {
                    this.SevenMoreAxleMultiTrailerTruckField = value;
                    this.RaisePropertyChanged("SevenMoreAxleMultiTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteIDField, value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SixAxleMultiTrailerTruck {
            get {
                return this.SixAxleMultiTrailerTruckField;
            }
            set {
                if ((this.SixAxleMultiTrailerTruckField.Equals(value) != true)) {
                    this.SixAxleMultiTrailerTruckField = value;
                    this.RaisePropertyChanged("SixAxleMultiTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SixOrMoreAxleSignleTrailerTruck {
            get {
                return this.SixOrMoreAxleSignleTrailerTruckField;
            }
            set {
                if ((this.SixOrMoreAxleSignleTrailerTruckField.Equals(value) != true)) {
                    this.SixOrMoreAxleSignleTrailerTruckField = value;
                    this.RaisePropertyChanged("SixOrMoreAxleSignleTrailerTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SpMean {
            get {
                return this.SpMeanField;
            }
            set {
                if ((this.SpMeanField.Equals(value) != true)) {
                    this.SpMeanField = value;
                    this.RaisePropertyChanged("SpMean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ThreeAxleSingleUnitTruck {
            get {
                return this.ThreeAxleSingleUnitTruckField;
            }
            set {
                if ((this.ThreeAxleSingleUnitTruckField.Equals(value) != true)) {
                    this.ThreeAxleSingleUnitTruckField = value;
                    this.RaisePropertyChanged("ThreeAxleSingleUnitTruck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeCaptured {
            get {
                return this.TimeCapturedField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeCapturedField, value) != true)) {
                    this.TimeCapturedField = value;
                    this.RaisePropertyChanged("TimeCaptured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TruckCount {
            get {
                return this.TruckCountField;
            }
            set {
                if ((this.TruckCountField.Equals(value) != true)) {
                    this.TruckCountField = value;
                    this.RaisePropertyChanged("TruckCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TwoAxleFourTires {
            get {
                return this.TwoAxleFourTiresField;
            }
            set {
                if ((this.TwoAxleFourTiresField.Equals(value) != true)) {
                    this.TwoAxleFourTiresField = value;
                    this.RaisePropertyChanged("TwoAxleFourTires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TwoAxleSixTires {
            get {
                return this.TwoAxleSixTiresField;
            }
            set {
                if ((this.TwoAxleSixTiresField.Equals(value) != true)) {
                    this.TwoAxleSixTiresField = value;
                    this.RaisePropertyChanged("TwoAxleSixTires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Vpp85 {
            get {
                return this.Vpp85Field;
            }
            set {
                if ((this.Vpp85Field.Equals(value) != true)) {
                    this.Vpp85Field = value;
                    this.RaisePropertyChanged("Vpp85");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="spTCSpeedSummaryBySite_Result", Namespace="http://schemas.datacontract.org/2004/07/TrafficCount.Domain")]
    [System.SerializableAttribute()]
    public partial class spTCSpeedSummaryBySite_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LaneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp0To10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp100To110Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp10To20Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp110To120Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp120To130Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp130To140Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp140To150Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp150To160Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp160To200Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp20To30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp30To40Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp40To50Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp50To60Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp60To70Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp70To80Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp80To90Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sp90To100Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SpMeanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeCapturedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> Vpp85Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bound {
            get {
                return this.BoundField;
            }
            set {
                if ((object.ReferenceEquals(this.BoundField, value) != true)) {
                    this.BoundField = value;
                    this.RaisePropertyChanged("Bound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lane {
            get {
                return this.LaneField;
            }
            set {
                if ((object.ReferenceEquals(this.LaneField, value) != true)) {
                    this.LaneField = value;
                    this.RaisePropertyChanged("Lane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteIDField, value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp0To10 {
            get {
                return this.Sp0To10Field;
            }
            set {
                if ((this.Sp0To10Field.Equals(value) != true)) {
                    this.Sp0To10Field = value;
                    this.RaisePropertyChanged("Sp0To10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp100To110 {
            get {
                return this.Sp100To110Field;
            }
            set {
                if ((this.Sp100To110Field.Equals(value) != true)) {
                    this.Sp100To110Field = value;
                    this.RaisePropertyChanged("Sp100To110");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp10To20 {
            get {
                return this.Sp10To20Field;
            }
            set {
                if ((this.Sp10To20Field.Equals(value) != true)) {
                    this.Sp10To20Field = value;
                    this.RaisePropertyChanged("Sp10To20");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp110To120 {
            get {
                return this.Sp110To120Field;
            }
            set {
                if ((this.Sp110To120Field.Equals(value) != true)) {
                    this.Sp110To120Field = value;
                    this.RaisePropertyChanged("Sp110To120");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp120To130 {
            get {
                return this.Sp120To130Field;
            }
            set {
                if ((this.Sp120To130Field.Equals(value) != true)) {
                    this.Sp120To130Field = value;
                    this.RaisePropertyChanged("Sp120To130");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp130To140 {
            get {
                return this.Sp130To140Field;
            }
            set {
                if ((this.Sp130To140Field.Equals(value) != true)) {
                    this.Sp130To140Field = value;
                    this.RaisePropertyChanged("Sp130To140");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp140To150 {
            get {
                return this.Sp140To150Field;
            }
            set {
                if ((this.Sp140To150Field.Equals(value) != true)) {
                    this.Sp140To150Field = value;
                    this.RaisePropertyChanged("Sp140To150");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp150To160 {
            get {
                return this.Sp150To160Field;
            }
            set {
                if ((this.Sp150To160Field.Equals(value) != true)) {
                    this.Sp150To160Field = value;
                    this.RaisePropertyChanged("Sp150To160");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp160To200 {
            get {
                return this.Sp160To200Field;
            }
            set {
                if ((this.Sp160To200Field.Equals(value) != true)) {
                    this.Sp160To200Field = value;
                    this.RaisePropertyChanged("Sp160To200");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp20To30 {
            get {
                return this.Sp20To30Field;
            }
            set {
                if ((this.Sp20To30Field.Equals(value) != true)) {
                    this.Sp20To30Field = value;
                    this.RaisePropertyChanged("Sp20To30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp30To40 {
            get {
                return this.Sp30To40Field;
            }
            set {
                if ((this.Sp30To40Field.Equals(value) != true)) {
                    this.Sp30To40Field = value;
                    this.RaisePropertyChanged("Sp30To40");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp40To50 {
            get {
                return this.Sp40To50Field;
            }
            set {
                if ((this.Sp40To50Field.Equals(value) != true)) {
                    this.Sp40To50Field = value;
                    this.RaisePropertyChanged("Sp40To50");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp50To60 {
            get {
                return this.Sp50To60Field;
            }
            set {
                if ((this.Sp50To60Field.Equals(value) != true)) {
                    this.Sp50To60Field = value;
                    this.RaisePropertyChanged("Sp50To60");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp60To70 {
            get {
                return this.Sp60To70Field;
            }
            set {
                if ((this.Sp60To70Field.Equals(value) != true)) {
                    this.Sp60To70Field = value;
                    this.RaisePropertyChanged("Sp60To70");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp70To80 {
            get {
                return this.Sp70To80Field;
            }
            set {
                if ((this.Sp70To80Field.Equals(value) != true)) {
                    this.Sp70To80Field = value;
                    this.RaisePropertyChanged("Sp70To80");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp80To90 {
            get {
                return this.Sp80To90Field;
            }
            set {
                if ((this.Sp80To90Field.Equals(value) != true)) {
                    this.Sp80To90Field = value;
                    this.RaisePropertyChanged("Sp80To90");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sp90To100 {
            get {
                return this.Sp90To100Field;
            }
            set {
                if ((this.Sp90To100Field.Equals(value) != true)) {
                    this.Sp90To100Field = value;
                    this.RaisePropertyChanged("Sp90To100");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SpMean {
            get {
                return this.SpMeanField;
            }
            set {
                if ((this.SpMeanField.Equals(value) != true)) {
                    this.SpMeanField = value;
                    this.RaisePropertyChanged("SpMean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeCaptured {
            get {
                return this.TimeCapturedField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeCapturedField, value) != true)) {
                    this.TimeCapturedField = value;
                    this.RaisePropertyChanged("TimeCaptured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Vpp85 {
            get {
                return this.Vpp85Field;
            }
            set {
                if ((this.Vpp85Field.Equals(value) != true)) {
                    this.Vpp85Field = value;
                    this.RaisePropertyChanged("Vpp85");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TCService.ITCSummary")]
    public interface ITCSummary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetUserNameByLogin", ReplyAction="http://tempuri.org/ITCSummary/GetUserNameByLoginResponse")]
        string[] GetUserNameByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetTCAxlesDetailsBySite", ReplyAction="http://tempuri.org/ITCSummary/GetTCAxlesDetailsBySiteResponse")]
        TrafficCount.Presentation.TCService.spTCAxlesDetails_Result[] GetTCAxlesDetailsBySite(string SiteID, System.DateTime dateCaptured);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetTCSpeedDetailsBySite", ReplyAction="http://tempuri.org/ITCSummary/GetTCSpeedDetailsBySiteResponse")]
        TrafficCount.Presentation.TCService.spTCSpeedDetails_Result[] GetTCSpeedDetailsBySite(string SiteID, System.DateTime dateCaptured);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetTCSummaryByLoc", ReplyAction="http://tempuri.org/ITCSummary/GetTCSummaryByLocResponse")]
        TrafficCount.Presentation.TCService.spTCSummaryByLoc_Result[] GetTCSummaryByLoc(string Road1, string Road2, string Dir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetTCSummaryBySite", ReplyAction="http://tempuri.org/ITCSummary/GetTCSummaryBySiteResponse")]
        TrafficCount.Presentation.TCService.spTCSummaryBySite_Result[] GetTCSummaryBySite(string SiteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetTCSummaryOneBySite", ReplyAction="http://tempuri.org/ITCSummary/GetTCSummaryOneBySiteResponse")]
        TrafficCount.Presentation.TCService.spTCSummaryOneBySite_Result[] GetTCSummaryOneBySite(string SiteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetTCAxlesSummaryBySite", ReplyAction="http://tempuri.org/ITCSummary/GetTCAxlesSummaryBySiteResponse")]
        TrafficCount.Presentation.TCService.spTCAxlesSummaryBySite_Result[] GetTCAxlesSummaryBySite(string SiteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetTCSpeedSummaryBySite", ReplyAction="http://tempuri.org/ITCSummary/GetTCSpeedSummaryBySiteResponse")]
        TrafficCount.Presentation.TCService.spTCSpeedSummaryBySite_Result[] GetTCSpeedSummaryBySite(string SiteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetRoad1", ReplyAction="http://tempuri.org/ITCSummary/GetRoad1Response")]
        string[] GetRoad1(string RoadName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetRoad2", ReplyAction="http://tempuri.org/ITCSummary/GetRoad2Response")]
        string[] GetRoad2(string RoadName1, string RoadName2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetSiteID", ReplyAction="http://tempuri.org/ITCSummary/GetSiteIDResponse")]
        string[] GetSiteID(string siteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetXY", ReplyAction="http://tempuri.org/ITCSummary/GetXYResponse")]
        string GetXY(string firstName, string secondName, string dir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCSummary/GetXYBySite", ReplyAction="http://tempuri.org/ITCSummary/GetXYBySiteResponse")]
        string GetXYBySite(string siteID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITCSummaryChannel : TrafficCount.Presentation.TCService.ITCSummary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCSummaryClient : System.ServiceModel.ClientBase<TrafficCount.Presentation.TCService.ITCSummary>, TrafficCount.Presentation.TCService.ITCSummary {
        
        public TCSummaryClient() {
        }
        
        public TCSummaryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCSummaryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCSummaryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCSummaryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetUserNameByLogin(string login) {
            return base.Channel.GetUserNameByLogin(login);
        }
        
        public TrafficCount.Presentation.TCService.spTCAxlesDetails_Result[] GetTCAxlesDetailsBySite(string SiteID, System.DateTime dateCaptured) {
            return base.Channel.GetTCAxlesDetailsBySite(SiteID, dateCaptured);
        }
        
        public TrafficCount.Presentation.TCService.spTCSpeedDetails_Result[] GetTCSpeedDetailsBySite(string SiteID, System.DateTime dateCaptured) {
            return base.Channel.GetTCSpeedDetailsBySite(SiteID, dateCaptured);
        }
        
        public TrafficCount.Presentation.TCService.spTCSummaryByLoc_Result[] GetTCSummaryByLoc(string Road1, string Road2, string Dir) {
            return base.Channel.GetTCSummaryByLoc(Road1, Road2, Dir);
        }
        
        public TrafficCount.Presentation.TCService.spTCSummaryBySite_Result[] GetTCSummaryBySite(string SiteID) {
            return base.Channel.GetTCSummaryBySite(SiteID);
        }
        
        public TrafficCount.Presentation.TCService.spTCSummaryOneBySite_Result[] GetTCSummaryOneBySite(string SiteID) {
            return base.Channel.GetTCSummaryOneBySite(SiteID);
        }
        
        public TrafficCount.Presentation.TCService.spTCAxlesSummaryBySite_Result[] GetTCAxlesSummaryBySite(string SiteID) {
            return base.Channel.GetTCAxlesSummaryBySite(SiteID);
        }
        
        public TrafficCount.Presentation.TCService.spTCSpeedSummaryBySite_Result[] GetTCSpeedSummaryBySite(string SiteID) {
            return base.Channel.GetTCSpeedSummaryBySite(SiteID);
        }
        
        public string[] GetRoad1(string RoadName) {
            return base.Channel.GetRoad1(RoadName);
        }
        
        public string[] GetRoad2(string RoadName1, string RoadName2) {
            return base.Channel.GetRoad2(RoadName1, RoadName2);
        }
        
        public string[] GetSiteID(string siteID) {
            return base.Channel.GetSiteID(siteID);
        }
        
        public string GetXY(string firstName, string secondName, string dir) {
            return base.Channel.GetXY(firstName, secondName, dir);
        }
        
        public string GetXYBySite(string siteID) {
            return base.Channel.GetXYBySite(siteID);
        }
    }
}
